// indexstyle.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#1E1E1E", padding: 20 },
  albumSelector: {
    backgroundColor: "#333",
    padding: 10,
    borderRadius: 10,
    marginBottom: 15,
  },
  selectAlbumText: { color: "grey", textAlign: "center" },
  albumInfo: { flexDirection: "row", alignItems: "center" },
  albumImage: { width: 50, height: 50, marginRight: 10 },
  albumTitle: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
    maxWidth: 275,
    overflow: "hidden",
    textAlign: "left",
  },
  albumYear: { color: "gray", fontSize: 12, marginTop: 5 },
  picker: { backgroundColor: "#333", color: "white", marginBottom: 15 },
  modalContainer: {
    flex: 1,
    backgroundColor: "#1E1E1E",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 105,
    paddingHorizontal: 20,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#333",
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
  },
  icon: { marginRight: 10 },
  searchInput: { flex: 1, color: "white", fontSize: 16 },
  clearButton: { marginLeft: 10 },
  albumItem: { alignItems: "center", width: "48%", marginBottom: 15 },
  albumThumbnail: { width: "100%", height: 150, borderRadius: 8 },
  albumName: { color: "white", fontSize: 14, textAlign: "center", marginTop: 5 },
  resultsList: { paddingHorizontal: 10 },
  closeButtonText: { color: "white", fontSize: 16, fontWeight: "bold" },
  dateButton: {
    backgroundColor: "#333",
    paddingHorizontal: 15,
    borderRadius: 10,
    marginBottom: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 50,
    width: "100%",
    marginHorizontal: 0,
  },
  dateTextContainer: {
    flex: 1,
    justifyContent: "center",
  },
  dateText: {
    color: "white",
    fontSize: 16,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  starRow: { flexDirection: "row", alignItems: "center" },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    padding: 0,
    paddingBottom: 15,
    borderRadius: 10,
    justifyContent: "left",
  },
  ratingWrapper: { alignItems: "flex-start" },
  ratingText: {
    color: "lightgray",
    paddingTop: 10,
    fontSize: 18,
    marginBottom: 5,
  },
  textInput: {
    backgroundColor: "#333",
    color: "white",
    padding: 10,
    borderRadius: 10,
    height: 330,
    textAlignVertical: "top",
    marginBottom: 15,
  },
  saveButton: {
    backgroundColor: "#007AFF",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 15,
  },
  saveButtonText: { color: "white", fontWeight: "bold" },
  closeButton: {
    position: "absolute",
    top: 60,
    left: 10,
    zIndex: 10,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  searchHistoryContainer: { width: "100%", marginBottom: 15 },
  searchHistoryTitle: { color: "white", fontSize: 16, fontWeight: "bold" },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 8,
    marginBottom: 5,
  },
  historyText: { color: "lightgrey", fontSize: 14 },
  clearHistoryButton: { alignItems: "center" },
  clearHistoryButtonText: { color: "white", fontSize: 14 },
  noHistoryText: { color: "gray", fontSize: 14, textAlign: "center" },
  searchHistoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  updateButton: {
    backgroundColor: "#4CAF50",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 15,
  },
  buttonText: { color: "white", fontWeight: "bold" },
  characterCount: {
    position: "absolute",
    top: -20,
    right: 5,
    color: "gray",
    fontSize: 12,
  },
});

export default styles;
